# Generated by Django 6.0.1 on 2026-01-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('amount', models.IntegerField()),
                ('biodegradable', models.BooleanField(default=False)),
                ('glowing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Replica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('drive', models.CharField(max_length=100)),
                ('hopUp', models.BooleanField(default=False)),
                ('energy', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('compatibility', models.ManyToManyField(related_name='attachments', to='api.replica')),
            ],
        ),
    ]
